spring:
  datasource:
    url: jdbc:mysql://43.201.135.252/networker
    username: root
    password: happyk!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: yuntyu01
    password: "앱 비밀번호"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  resources:
    static:
      location: classpath:/static/

  thymeleaf:
    prefix: classpath:/static/views/
    suffix: .html
    cache: false  
    mode: html
#    encoding: UTF-8
#    servlet:
#    content-type: text/html
file:
  upload-dir: ~/
